#//huangzhaosong 20151231 e---
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	:=  kxtj2_1009.o
#//huangzhaosong 20151231 e---
