## zhaozhensen 20160513 begin
ifeq ($(CONFIG_GOODIX_FINGERPRINT),y)
#obj-y := fpc1020_main.o fpc1020_common.o fpc1020_input.o fpc1020_capture.o
obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
else
obj-y := fpc1020_main.o fpc1020_common.o fpc1020_input.o fpc1020_capture.o
endif
## zhaozhensen 20160513 end